### ISSUE TITLE
[b1.2] The nether is missing it's red fog.

### ISSUE THREAD

**Issue by craftycodie** [craftycodie/Project-Poseidon-Uberbukkit#1]

**Comment by craftycodie** [comment]
Set the time to night in the nether for an aproximation.

**Comment by vrad-exe** [comment]
Servers with `hellworld` enabled show the actual Nether fog and the like, I guess it's not possible to swap that for a player who's already logged in though?

**Comment by craftycodie** [comment]
exactly, when i tried doing this for cloth it crashed the client
