### ISSUE TITLE
[b1.2] players can walk up stairs with fences below

### ISSUE THREAD

**Issue by craftycodie** [craftycodie/Project-Poseidon-Uberbukkit#8]

**Comment by vrad-exe** [comment]
More generally, it's not possible to get stuck on top of fences as it is on vanilla b1.2 servers. Although if you're trying to emulate the behavior of b1.2 singleplayer, then not getting stuck would be the correct behavior anyway.

**Comment by craftycodie** [comment]
I guess we could allow it given that there's no block protection, people can break the fence if need be
