### ISSUE TITLE
[b1.2] Levers don't appear to move when activated.

### ISSUE THREAD

**Issue by craftycodie** [craftycodie/Project-Poseidon-Uberbukkit#9]

**Comment by hdfsyu** [comment]
Pretty weird, probably some sort of packet problem

**Comment by craftycodie** [comment]
I suspect it's something to do with the data values changing between b1.2 and b1.7.3

**Comment by hdfsyu** [comment]
Try removing b1.7.3 support and see if it works?

**Comment by craftycodie** [comment]
It doesn't On Feb 6, 2022 4:00 PM, Viyaan Chauhan ***@***.***> wrote:
Try removing b1.7.3 support and see if it works?

**Comment by hdfsyu** [comment]
oh

**Comment by craftycodie** [comment]
Vanilla issue
